### ISSUE TITLE
RaceID / StemID

### ISSUE THREAD

**Issue by zouter** [dynverse/dynmethods#55] opened 2018-06-20 10:16 UTC
Hello @dgrun and @avolab

This issue is for discussing the wrapper for your trajectory inference method, RaceID / StemID, which we wrapped for our benchmarking study ([10.1101/276907](https://doi.org/10.1101/276907)). In our [dynmethods](https://github.com/dynverse/dynmethods) framework, we collected some meta information about your method, and created a docker wrapper so that all methods can be easily run and compared. The code for this wrapper is located in [a docker container](https://github.com/dynverse/dynmethods/tree/devel/containers/raceid_stemid). The way this container is structured is described in [this vignette](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html).

We are creating this issue to ensure your method is being evaluated in the way it was designed for. The checklist below contains some important questions for you to have a look at.

- [ ] **Parameters**, defined in [definition.yml](https://github.com/dynverse/dynmethods/tree/devel/containers/raceid_stemid/definition.yml) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#parameters))
  - Are all important parameters described in this file?
  - For each parameter, is the proposed default value reasonable?
  - For each parameter, is the proposed parameter space reasonable (e.g. lower and upper boundaries)?
  - Is the description of the parameters correct and up-to-date?
- [ ] **Input**, defined in [definition.yml](https://github.com/dynverse/dynmethods/tree/devel/containers/raceid_stemid/definition.yml) and loaded in [run.R](https://github.com/dynverse/dynmethods/tree/devel/containers/raceid_stemid/run.R) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#input))
  - Is the correct type of expression requested (raw counts or normalised expression)?
  - Is all prior information (required or optional) requested?
  - Would some other type of prior information help the method?
- [ ] **Output**, defined in [definition.yml](https://github.com/dynverse/dynmethods/tree/devel/containers/raceid_stemid/definition.yml) and saved in [run.R](https://github.com/dynverse/dynmethods/tree/devel/containers/raceid_stemid/run.R) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#output))
  - Is the output correctly processed towards the [common trajectory model](https://github.com/dynverse/dynwrap#dynwrap)? Would some other postprocessing method make more sense?
  - Is all relevant output saved (dimensionality reduction, clustering/grouping, pseudotime, ...)
- [ ] **Wrapper script**, see [run.R](https://github.com/dynverse/dynmethods/tree/devel/containers/raceid_stemid/run.R) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#doing-trajectory-inference))
  - This is a script that is executed upon starting the docker container. It will receive several input files as defined by `definition.yml`, and is expected to produce certain output files, also as defined by `definition.yml`.
  - Is the script a correct representation of the general workflow a user is expected to follow when they want to apply your method to their data?
- [ ] **Quality control**, see [the qc worksheet](https://docs.google.com/spreadsheets/d/1GWWdndfTPtXPsCXK07jU03MmhIJHmv28E7YiMnQ_0Xo//edit#gid=353963991)
  - We also evaluated the implementation of a method based on a large check list of good software software development practices.
  - Are the answers we wrote down for your method correct and up to date? Do you disagree with certain answers? (Feel free to leave a comment in the worksheet)
    - You can improve the QC score of your method by implementing the required changes and letting us know. *Do not gloss over this, as it is the easiest way to improve the overall ranking of your TI method in our study!*

The most convenient way for you to test and adapt the wrapper is to install [dyno](https://github.com/dynverse/dyno), download and modify [these files](https://github.com/dynverse/dynmethods/tree/devel/containers/raceid_stemid), and run your method on a dataset of interest or one of our synthetic toy datasets. This is further described in [this vignette](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html). Once finished, we prefer that you [fork the dynmethods repository](https://github.com/dynverse/dynmethods), make the necessary changes, and send us a pull request. Alternatively, you can also send us the files and we will make the necessary changes.

If you have any further questions or remarks, feel free to reply to this issue.

Kind regards,
@zouter and @rcannood

**Comment by dgrun** [comment] 2018-06-21 19:56
Hi,

I would like to test the method but I run into problems with the docker
container on MacOS.

I cannot get rid of this error message:


docker: Error response from daemon: Mounts denied:

The paths
/var/folders/qr/60yvs97j7j1d3fgzhl43hh900000gq/T//RtmpKWMHBy/output and
/var/folders/qr/60yvs97j7j1d3fgzhl43hh900000gq/T//RtmpKWMHBy/input

are not shared from OS X and are not known to Docker.

You can configure shared paths from Docker -> Preferences... -> File
Sharing.

See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.

.

ERRO[0000] error waiting for container: context canceled

*Error in infer_trajectory(task, ti_comp1()) : *

*  Error during trajectory inference *

*list(message = "cannot open the connection", call = gzfile(file, "rb"))*

*In addition: Warning message:*

*In gzfile(file, "rb") :*

*  cannot open compressed file
'/var/folders/qr/60yvs97j7j1d3fgzhl43hh900000gq/T//RtmpKWMHBy/output/output.rds',
probable reason 'No such file or directory'*

This problem is apparently known for MacOS but I could not fix it.

Many thanks!
Dominic

**Comment by rcannood** [comment] 2018-06-22 09:40
Hello Dominic!

Thanks for trying out dynwrap, and for finding out about this problem. @zouter and I should really have a look at getting a Mac OS X testbed for situations like this.

Based on your the error messages you're getting, I tried implementing a fix. Could you try installing the devel branch of dynwrap to see if it works? (`devtools::install_github("dynverse/dynwrap@devel")`).

In the meantime, I'll try to find a better way of testing out our code on Mac OS X (other than travis).

Robrecht

**Comment by dgrun** [comment] 2018-06-22 13:30
Hi Robrecht,

I tried and got another error message this time:

> model <- infer_trajectory(task, ti_comp1())

*Error in infer_trajectory(task, ti_comp1()) : *

*  Error during trajectory inference *

*list(message = "object 'dir_output' not found", call = eval(parse(text =
code, keep.source = FALSE), envir))*

>

Could you help?

Best,
Dominic

**Comment by rcannood** [comment] 2018-06-22 14:18
That's an interesting error. I assume you're attempting to replicate the code from [this link](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html)? Right now, I haven't managed to reproduce the error. Is the following the code you're trying to run?

Kind regards,
Robrecht


``` R
> devtools::install_github("dynverse/dynwrap@devel", dep = TRUE, upgr = TRUE)
....... lots of output ...
** testing if installed package can be loaded
* DONE (dynwrap)
Using GitHub PAT from envvar GITHUB_PAT
Using GitHub PAT from envvar GITHUB_PAT
Using GitHub PAT from envvar GITHUB_PAT
Using GitHub PAT from envvar GITHUB_PAT
Using GitHub PAT from envvar GITHUB_PAT
> 
> library(tidyverse)
> ti_comp1 <- pull_docker_ti_method("dynverse/comp1")
Using default tag: latest
latest: Pulling from dynverse/comp1
Digest: sha256:47626520d6ed83ef5deb932b3b510af5b4a3cd9e2a874cfe035b43e73539fa81
Status: Image is up to date for dynverse/comp1:latest
804a48714cee8b1ef20f36a24114dc57f9144b11acbaece6c7cac121a509406e
> 
> 
> ncells <- 1000
> pseudotime <- runif(ncells)
> 
> expression <- matrix(
+   c(
+     (pseudotime - 0.5) ** 2,
+     sqrt(pseudotime + 20),
+     pseudotime
+   ),
+   ncol = 3,
+   dimnames = list(as.character(rep(seq_len(ncells))), as.character(c("A", "B", "C")))
+ )
> expression <- expression + rnorm(length(expression), sd = 0.02)
> 
> start_id = rownames(expression)[which.min(pseudotime)]
> 
> counts <- round(expression)
> 
> task <- wrap_expression(
+   expression,
+   counts
+ ) %>% add_prior_information(start_id = start_id)
> 
> model <- infer_trajectory(task, ti_comp1())
> dynplot::plot_graph(model)
```

**Comment by dgrun** [comment] 2018-06-22 14:46
Yes, exactly.

Best,
Dominic

On Fri, Jun 22, 2018 at 4:18 PM, Robrecht Cannoodt <notifications@github.com

**Comment by rcannood** [comment] 2018-06-22 15:12
Aha. It was a copy paste error i made, and @zouter fixed it shortly afterwards. Could you try reinstalling dynwrap@devel and try again? 

Sorry for this :)

**Comment by dgrun** [comment] 2018-06-22 18:55
On step further... now StemID2 runs, but it does not finish.

This is the error message:

Error in if (coef(fit)[3] >= 0 | mm >= -1) { :

  missing value where TRUE/FALSE needed

Calls: do.call ... withVisible -> <Anonymous> -> <Anonymous> -> <Anonymous>

Execution halted

*Error in infer_trajectory(task, ti_comp1()) : *

*  Error during trajectory inference *

*list(message = "cannot open the connection", call = gzfile(file, "rb"))*

*In addition: Warning message:*

*In gzfile(file, "rb") :*

*  cannot open compressed file
'/tmp/folders/qr/60yvs97j7j1d3fgzhl43hh900000gq/T//RtmpzPQUD8/output/output.rds',
probable reason 'No such file or directory'*

>

Thanks,
Dominic

On Fri, Jun 22, 2018 at 5:12 PM, Robrecht Cannoodt <notifications@github.com

**Comment by zouter** [comment] 2018-06-23 10:09
Hi Dominic

This looks like an error specific to StemID2, as it errors at this line: https://github.com/dynverse/StemID2/blob/master/R/RaceID3_StemID2_class.R#L98 . Either `coef(fit)[3]` or `mm` are NA at that point in the code.

StemID2 runs fine on our test datasets, eg. on a (simple) linear dataset:
![image](https://user-images.githubusercontent.com/5727377/41808463-29a59264-76de-11e8-8d36-d1574bfc706e.png)

**Comment by dgrun** [comment] 2018-06-23 12:06
Yes, I saw that this was an error in StemID2 but I've never seen this error
before and I just ran your sample code:
https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html
If I understand you right, you don't get the error with the identical code?

Thanks,
Dominic

**Comment by dgrun** [comment] 2018-06-25 08:50
Dear Wouter,

I cannot test the method since I did not manage to fix the error. Therefore
I'm not sure if your parameter settings are reasonable.
A few remarks: Please test both modes of StemID/StemID2, nmode=TRUE and
nmode=FALSE
I'm using normally pethr=0.01, but this could depend on the data as well...

To extract the lineage grah (i.e. the significant links) you can use
ltr@cdata$pvn.e, but you should also apply filtering by linkscore
(ltr@cdata$linkscore).
This is usually informed by visual inspection. If some links are very
strong this gives a hint of how to choose the threshold. However, if only
weak links are present for a given cluster I normally do not filter based
on linkscore.
A good default value is 0.2.

I played a bit with the test data from this link:
https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html

Apparently, it has only three features (genes). I think the background
model of RaceID will be completely useless here, since it is fitted to the
ensemble of all genes and is based on the negative binomial distribution
observed for UMI counts. StemID/RaceID can only work well under these
conditions...

I could get the test data to work after scaling up the expression to
expected levels, e.g. by mutliplying with 1,000. I can then reproduce the
linear trajectory. However, I believe that the data are not well suited for
RaceID/StemID analysis.

It would be great if I could also test more complex trajectories. Would you
have code for this?

Thanks a lot!

Best regards,
Dominic

**Comment by zouter** [comment] 2018-06-25 12:40
Hi Dominic

You're certainly right that the example data from the vignette is not complex enough, and when using the same data as you did I also get the same error. I guess a lot of methods will fail when using 3 genes and it is certainly not a relevant use case, so we can ignore it. I will update this in the vignette.

To test a method, we usually use those generated by dynverse/dyntoy package. These datasets are very simple in the sense that the trajectory can be easily seen on a 2D dimensionality reduction, so it is a good initial test for a method. If a method does not perform well on such simple data, it will probably also not work well on the more complex real and/or synthetic data.

```r
library(dynmethods)

# devtools::install_github("dynverse/dyntoy")
task <- dyntoy::generate_dataset(
  model = dyntoy::model_bifurcating(1), 
  num_cells = 200, 
  num_genes = 200
)

method <- ti_stemid2()

model <- dynwrap::infer_trajectory(task, method)
```

Both StemID and StemID2 run without errors, and generate a reasonable trajectory (for StemID2):

```r
# devtools::install_github("dynverse/dynplot")
dynplot::plot_dimred(model)
```

![image](https://user-images.githubusercontent.com/5727377/41848298-4cad3834-787d-11e8-8ebb-b4c5639e3359.png)

Although the actual underlying topology contains a lot of extra edges:

```r
dynplot::plot_topology(model)
```
![image](https://user-images.githubusercontent.com/5727377/41848320-5de522ce-787d-11e8-96c2-2b18d08d12cd.png)

Based on your suggestions: 
- In commit a74e690a5b3271a10427b5a6f023e6811f95b899 , StemID and Stemid2 now use the raw counts instead of normalised expression. This was an oversight on our part.
- In commit 16c9d293a144ee8a3b30920aeed2c068cedf6503 I tried including the edge significance in the wrapper.

However, on some toy data this leads to some clusters being disconnected:

![image](https://user-images.githubusercontent.com/5727377/41849612-d163ee84-7881-11e8-8771-af905593f538.png)

Perhaps some automatic selection of the pvalue_cutoff and linkscore_cutoff could help with this. I understand this can be done visually, but of course this would make it impossible for us to evaluate the method on several datasets... So we'll have to use some reasonable default values which work in most use cases.

Of course you can also test the methods using the synthetic data and real data from the preprint (https://zenodo.org/record/1211533 ). In most cases these contain count data, although not all are UMI based depending on the underlying single-cell technology. We're now cleaning up the code a little bit so that the use of these datasets will be easier in the future.

Hope this helps

Wouter

**Comment by dgrun** [comment] 2018-06-25 14:06
Dear Wouter,

many thanks. I think there is still a problem with the statistics of the
simulated expression. These features do not follow a negative binomial
distribution and the outlier model of RaceID produces nonsense results. I
don't think these test data will help to evaluate the performance of
StemID/StemID2, since these methods rely on meaningful clustering.
For this reason I also don't know how to select default values for the
linkscore and the p-value. Probably, the linkscore should be disregarded in
this case. For the p-value, maybe 0.01 or 0.001 or both?
It is also important to set FSelect=FALSE, since RaceID's feature selection
relies on an appropriate background model which is not available for the
simulated data.
For this reason, outliers should not be detected, i.e. set probthr=0.
This makes the whole RaceID clustering procedure questionable, since it
only relies on a very rough initial estimation of the cluster number and a
correction of the clustering in the outlier identification step of the
procedure.

We deliberately designed RaceID this way, since it shows very good
performance on UMI data, and we point out in the manuscript that it is not
designed for non-UMI data.

It would therefore be good to limit the benchmarking of StemID/StemID2 to
datasets with statistics similar to UMI counts, if possible.

Best wishes,
Dominic

**Comment by dgrun** [comment] 2018-06-28 17:21
Dear Wouter,

just to add - if you still wish to include StemID in the benchmarking with
non-UMI data, there should be a disclaimer in the manuscript pointing out
that the method cannot show good performance on such data by design.

Hope this is possible. Thanks!

Best wishes,
Dominic

**Comment by zouter** [comment] 2018-06-28 17:41
Hi Dominic

The toy data I described in the previous post is simply used as a quick test for the methods. It is to see whether the method produces sensible output on very simple and clear-cut data. These datasets are not used for the evaluation, where we use more realistic simulated data which all do follow a (zero inflated) negative binomial distribution. The way these simulated datasets are distributed are all based on the distribution of real datasets (using the splatter framework).

**Comment by dgrun** [comment] 2018-06-28 17:47
Ok, that's great! Is it possible to test the method on such data to let you
know about the suitable parameter choices?

**Comment by zouter** [comment] 2018-06-28 18:03
Certainly! It's at the top of my to-do list to get all the datasets back in the right format for testing. I will get back to you (hopefully tomorrow) with an example script.

**Comment by rcannood** [comment] 2018-08-07 08:31
I updated the container to use the RaceID package from CRAN instead of the github scripts. The code seems to have been improved greatly. As a result, the [QC score](https://docs.google.com/spreadsheets/d/1GWWdndfTPtXPsCXK07jU03MmhIJHmv28E7YiMnQ_0Xo/edit#gid=353963991) has also increased.

**Comment by rcannood** [comment] 2019-07-02 12:23
Closing this issue. Feel free to create a pull request on [dynverse/ti_raceid_stemid](https://github.com/dynverse/ti_raceid_stemid) if you find any improvements to the code.

**Closed by rcannood** 2019-07-02 12:23 UTC
Labels: method_discussion
